### ISSUE TITLE
colab notebook for the project

### ISSUE THREAD

**Issue by GeorvityLabs** [simon3dv/SLR-SFS#1]
This project looks amazing.
Is it possible to make a colab notebook to test out this project.
Maybe the output could be either .mp4 , also possibly if any other format can be generated , for eg : something that can be imported into blender.

**Comment by simon3dv** [comment]
Sure. I am still updating this project. A colab notebook to generate .mp4 may be updated soon.

**Comment by GeorvityLabs** [comment]
> Sure. I am still updating this project. A colab notebook to generate .mp4 may be updated soon.

great , looking forward to it.

**Comment by simon3dv** [comment]
Hi @GeorvityLabs , the colab noteook is updated. Please contact me if you have any questions.

**Comment by GeorvityLabs** [comment]
awesome , thanks @simon3dv
